### ISSUE TITLE
Не запускается abot_drivers

### ISSUE THREAD

**Issue by mrsmtvd** [amperka/abot#2]
Добрый день.
Надеюсь на вашу помощь.

Следую туториалу на amperka. Пытаюсь запустить двигатели в первый раз. Значения с датчика холла приходят, скорость, углы - все ОК.

При попытке запустить двигатели и задать скорость ничего не происходит.
А в консоли на Raspberi Pi warning:

Waiting for first setpoint message

Судя по исходникам библиотеки это из-за
!ros::topic::waitForMessage<std_msgs::Float64>(setpoint_topic_, [ros::Duration])

Уже пробовал remap менять, вручную задавать разные значения
Ничего не помогает

**Comment by gabbapeople** [comment]
Привет! @vdunaev 

Можно чуток подробнее.
- Какая OS? Какая распберри?
- Как пытаетесь запустить моторы? Каким кодом, библиотекой / нодой (через wiringPi?)
- Какой драйвер моторов (плата)
- Было бы круто более подробный лог из консоли или даже скрин

**Comment by mrsmtvd** [comment]
@gabbapeople спасибо за ответ

- Ubuntu 20.04.5
- Raspberry Pi 4 Model B (4gb)
- Пакет 1 в 1 из репозитория abot_driver (кроме пока лидара)
`<launch>
	<node name="encoders" pkg="abot_driver" type="encoders" output="screen" />
	<node name="dc_motors" pkg="abot_driver" type="dc_motors" output="screen" />
	<include file="$(find abot_driver)/launch/abot_pid.launch" />
</launch>`
- Драйвер мотора как в статье - двухканальный Н-мост (Troyka-модуль), Troyka HAT

Версия ROS: (ядро)
PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14

**Comment by mrsmtvd** [comment]
Все шаги 1 в 1 как в статье
Значения с датчика холла приходят корректно

![Screenshot from 2022-10-03 13-23-22](https://user-images.githubusercontent.com/5794637/193555423-9d70f297-f090-4480-9bfb-8b4607428433.png)
![Screenshot from 2022-10-03 13-23-30](https://user-images.githubusercontent.com/5794637/193555429-42b64dcb-450d-4f2e-8418-b15dbc71440f.png)

**Comment by gabbapeople** [comment]
@vdunaev ну так по виду все работает.

Setpoint Warning - это пид контроллер ждет первое значение целевой скорости. 
Попробуйте вручную запаблишить скорость в топики `/abot/right_wheel/target_velocity` `/abot/left_wheel/target_velocity` из консоли командой `rostopic pub --once  /abot/right_wheel/target_velocity std_msgs/Float64` и далее значение скорости в формате yaml.  Можно после  `std_msgs/Float64` нажать TAB  и ROS cкопипастит шаблон синтаксиса.

**Comment by mrsmtvd** [comment]
Получилось только если сделать это на самом распбери.
Странно что в rqt топики видны, паблиш работает, но сообщения по факту не долетают до робота

**Comment by gabbapeople** [comment]
Не получилось запаблишить с другого компьютера в сети?
А топики запушенные на распберри видны с другой машины?

- Проверьте еще раз чтоб переменные окружения были правильно настроены.
`echo $ROS_MASTER_URI`
`echo $ROS_HOSTNAME`
`echo $ROS_IP`
- Проверьте чтоб в сети был только один мастер.
- Убедитесь что между компами работает ssh в обе стороны.
- Попробуйте с удаленной машины запаблишить в топик а на малине просто помониторить топик в терминале `rostopic echo`

**Comment by mrsmtvd** [comment]
@gabbapeople большое спасибо.
Проблема была в том, что я запускаю мастер в докере (т.к. ubuntu 22 версии на локальной машине)
И не прокинул туда ROS_HOSTNAME, ROS_IP

А лишь только ROS_MASTER_URI

docker run -it --name ros --network=host --rm --env="LIBGL_ALWAYS_SOFTWARE=1" --env="ROS_MASTER_URI=http://robot-user:11311" --env="ROS_HOSTNAME=robot-user" --env="ROS_IP=192.168.0.237"  --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --volume="/home/vasia/Robots/ros_src:/opt/ros/src" osrf/ros:noetic-desktop-full

В итоге заработало!
